In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("datasets/10M_sales_data_50products.csv")
df.describe()

       transaction_id      quantity    unit_price    total_bill
count    1.000000e+07  1.000000e+07  1.000000e+07  1.000000e+07
mean     5.000000e+06  3.000544e+00  1.505336e+02  4.516203e+02
std      2.886751e+06  1.414173e+00  2.306834e+02  7.941684e+02
min      1.000000e+00  1.000000e+00  1.058000e+01  1.058000e+01
25%      2.500001e+06  2.000000e+00  3.440000e+01  7.644000e+01
50%      5.000000e+06  3.000000e+00  5.923000e+01  1.692400e+02
75%      7.500000e+06  4.000000e+00  1.331000e+02  4.218300e+02
max      1.000000e+07  5.000000e+00  1.224000e+03  6.120000e+03

In [3]:
df.head()

,transaction_id,date,product_name,category,store_location,payment_method,quantity,discount_applied,unit_price,total_bill
0,1,2024-01-01,Bicycle Helmet,Sports,Phoenix,Credit Card,2,True,26.54,53.08
1,2,2024-09-10,External SSD 1TB,Electronics,Houston,Credit Card,5,False,107.87,539.35
2,3,2024-07-24,Gaming Laptop,Electronics,Los Angeles,Bank Transfer,4,False,1196.06,4784.24
3,4,2024-04-08,Sci-Fi Novel,Books,Houston,Credit Card,3,False,15.24,45.72
4,5,2024-06-09,Smart Watch,Electronics,Berlin,Debit Card,5,False,152.88,764.40

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000000 entries, 0 to 9999999
Data columns (total 10 columns):
 #   Column            Dtype
---  ------            -----
 0   transaction_id    int64
 1   date              object
 2   product_name      object
 3   category          object
 4   store_location    object
 5   payment_method    object
 6   quantity          int64
 7   discount_applied  bool
 8   unit_price        float64
 9   total_bill        float64
dtypes: bool(1), float64(2), int64(2), object(5)
memory usage: 696.2+ MB